/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ab3500',
        'primary-container': '#ff6b35',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59d',
        'on-primary': '#ffffff',
        'on-primary-container': '#5f1900',
        'on-primary-fixed': '#390c00',
        'on-primary-fixed-variant': '#832600',
        secondary: '#5d5c74',
        'secondary-container': '#e2e0fc',
        'secondary-fixed': '#e2e0fc',
        'secondary-fixed-dim': '#c6c4df',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#63627a',
        'on-secondary-fixed': '#1a1a2e',
        'on-secondary-fixed-variant': '#45455b',
        tertiary: '#006c49',
        'tertiary-container': '#00af79',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#003a25',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        background: '#f9f9ff',
        'on-background': '#151c27',
        surface: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-tint': '#ab3500',
        'surface-variant': '#dce2f3',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'surface-container-low': '#f0f3ff',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#151c27',
        'on-surface-variant': '#594139',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#8d7168',
        'outline-variant': '#e1bfb5',
        'inverse-primary': '#ffb59d',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Be Vietnam Pro"', 'sans-serif'],
        label: ['"Be Vietnam Pro"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 4px 20px rgba(0,0,0,0.08)',
        float: '0 8px 32px rgba(26, 26, 46, 0.06)',
        cta: '0 8px 24px rgba(255, 107, 53, 0.35)',
      },
    },
  },
  plugins: [],
}
